spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# H2 Consoleを有効にする
spring.h2.console.enabled=true
# テーブルを作成した直後に import.sql を実行させる設定

# もしSQLが実行されない場合は、以下も追加して明示的にファイルを指定します
spring.jpa.defer-datasource-initialization=true
# コンソールのパスを指定（デフォルトは /h2-console）
spring.h2.console.path=/h2-console
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
